language: haskell

ghc:
  - 7.6.3
  - 7.8.3

before_install:
  - export GHCVER=`ghc --numeric-version`

install:
  - cabal update
  - |
    if [ $GHCVER = "7.6.3" ]; then
      cabal install -j -fall --only-dependencies --enable-tests --constraint=containers==0.5.0.0
    else
      cabal install -j -fall --only-dependencies --enable-tests
    fi

script:
  - |
    cabal configure -fall --enable-tests
    cabal build
    cabal test
    make runtests
